
cc_binary(
    name = 'vcc',
    srcs = [
        'compile.cpp',
        'funclib.cpp',
        'lexical.cpp',
        'linked.cpp',
        'memstr.cpp',
        'preproc.cpp',
        'str.cpp',
        'tokenize.cpp',
        'vcc.cpp',

        'code.h',
        'compile.h',
        'funclib.h',
        'lexical.h',
        'linked.h',
        'memstr.h',
        'preproc.h',
        'str.h',
        'tokenize.h',
        'vcc.h',
        'vccode.h',
        'vector.h',
        'vtypes.h',
    ],

    copts = [
        '-g',
    ]
)
